# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 05:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import select_multiple_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from='name')),
                ('type', select_multiple_field.models.SelectMultipleField(choices=[('s', 'Singer'), ('m', 'MusicDirector'), ('l', 'Lyricist')], default='s', max_length=3)),
                ('bio', models.TextField(blank=True, null=True)),
                ('listed', models.BooleanField(default=True, help_text='Should this Artist be shown on the default list?', verbose_name='Include in listings')),
                ('disable_editing', models.BooleanField(default=False, help_text='Disable Editing. If verified by admin', verbose_name='Disable Editing')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists_creator', to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists_last_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
    ]
