# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='type',
            new_name='artisttype',
        ),
    ]
