# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 20:45
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20160321_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='summary',
            field=django_extensions.db.fields.json.JSONField(blank=True, null=True),
        ),
    ]
