# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20160316_2109'),
        ('artist', '0003_artist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lyricist',
        ),
        migrations.DeleteModel(
            name='MusicDirector',
        ),
        migrations.DeleteModel(
            name='Singer',
        ),
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together=set([('slug', 'type', 'name')]),
        ),
    ]
