# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:09
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20160316_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='type',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('Singer', 'Singer'), ('MusicDirector', 'MusicDirector'), ('Lyricist', 'Lyricist')], default='S', max_length=1),
        ),
    ]
