# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('slug', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016, verbose_name='year')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='lyricists',
            field=models.ManyToManyField(related_name='album', to='artist.Lyricist'),
        ),
        migrations.AddField(
            model_name='album',
            name='musicDirectors',
            field=models.ManyToManyField(related_name='album', to='artist.MusicDirector'),
        ),
        migrations.AddField(
            model_name='album',
            name='singers',
            field=models.ManyToManyField(related_name='album', to='artist.Singer'),
        ),
    ]
