# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lyrics', models.TextField(max_length=500)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Genre')),
                ('lyricist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Lyricist')),
                ('musdicDirector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.MusicDirector')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Singer')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
