# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20160225_0236'),
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyricist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='musdicDirector',
        ),
        migrations.RemoveField(
            model_name='song',
            name='singer',
        ),
        migrations.AddField(
            model_name='song',
            name='lyricists',
            field=models.ManyToManyField(blank=True, null=True, related_name='lyricist', to='artist.Lyricist'),
        ),
        migrations.AddField(
            model_name='song',
            name='musicDirectors',
            field=models.ManyToManyField(blank=True, null=True, related_name='musdicDirector', to='artist.MusicDirector'),
        ),
        migrations.AddField(
            model_name='song',
            name='singers',
            field=models.ManyToManyField(blank=True, null=True, related_name='singer', to='artist.Singer'),
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='song.Genre'),
        ),
    ]
