# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20160225_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyricists',
            field=models.ManyToManyField(blank=True, related_name='lyricist', to='artist.Lyricist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='musicDirectors',
            field=models.ManyToManyField(blank=True, related_name='musdicDirector', to='artist.MusicDirector'),
        ),
        migrations.AlterField(
            model_name='song',
            name='singers',
            field=models.ManyToManyField(blank=True, related_name='singer', to='artist.Singer'),
        ),
    ]
