# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artist'),
        ('song', '0003_auto_20160226_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyricists',
        ),
        migrations.RemoveField(
            model_name='song',
            name='musicDirectors',
        ),
        migrations.RemoveField(
            model_name='song',
            name='singers',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(blank=True, related_name='artist', to='artist.Artist'),
        ),
    ]
